blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Post_List.as_view(), name="blog"), #as_view 메소드를 사용해야 에러가 안 나고 잘나옴
    path('<uuid:pk>/', views.PostDetail.as_view() ), #inteager 타입으로 숫자를 pk로 의미한다.
    path('category/<str:slug>/', views.PostListByCategory.as_view()),
    path('tag/<str:slug>/', views.PostListByTag.as_view()),
    path('<uuid:pk>/update/', views.PostUpdate.as_view()),
    path('create/', views.PostCreate.as_view()),
    path('<uuid:pk>/new_comment/', views.new_comment),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('edit_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('search/<str:q>/', views.PostSearh.as_view()),
    # path('delete_comment/<int:pk>/', views.CommentDelete.as_view()),
]

django_my_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('basecamp.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import uuid

class Category(models.Model):
    name = models.CharField(max_length=25, unique=True) #카테고리 중복은 허용하지 않는다.
    description = models.TextField(blank=True)

    slug = models.SlugField(unique=True, allow_unicode=True) #unicode를 허용한다.. 한글..
    #slugfield는 독립성을 가질때 pk를 많이 사용했는데. 이번에는 그렇게 하지 않고 slug를 사용했다.

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/blog/category/{}/".format(self.slug)

    class Meta:
        verbose_name_plural = "categories"

class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/blog/tag/{}/".format(self.slug)

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=30)
    content = MarkdownxField()

    head_image = models.ImageField(upload_to="blog/%Y/%m/%d/", blank=True)

    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE) #검색 더해보세요.

    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL) #사용자 분
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta: #만든 순선대로 ..
        ordering = ['-created',]

    def __str__(self):
        return "{} :: {}".format(self.title, self.author)

    def get_absolute_url(self):
        return "/blog/{}/".format(self.pk)

    def get_update_url(self):
        return self.get_absolute_url() + 'update/'

    def get_markdown_content(self):
        return markdown(self.content)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = MarkdownxField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_markdown_content(self):
        return markdown(self.text)

    def get_absolute_url(self):
        return self.post.get_absolute_url() + '#comment-id-{}'.format(self.pk)

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

blog/views.py
from .models import Post, Category, Comment, Tag
from .forms import CommentForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.db.models import Q

class Post_List(ListView):
    model = Post
    paginate_by = 5
    # queryset = Post.objects.order_by("-created")

    # def get_queryset(self):
    #     return Post.objects.order_by("-created")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Post_List, self).get_context_data(**kwargs)
        context["category_list"] = Category.objects.all()
        context["posts_without_category"] = Post.objects.filter(category=None).count()

        return context

class PostSearh(Post_List):

    def get_queryset(self):
        q = self.kwargs['q']
        object_list = Post.objects.filter(Q(title__contains=q) | Q(content__contains=q))
        return object_list

    def get_context_data(self, *, object_list=None, **kwargs):
        content = super(PostSearh, self).get_context_data()
        content['search_info'] = 'Search: "{}"'.format(self.kwargs['q'])
        return content



class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *, object_list=None, **kwargs): #이거 강제 학습됬습니다.
        context = super(PostDetail, self).get_context_data(**kwargs)
        context["category_list"] = Category.objects.all()
        context["posts_without_category"] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm()
        return context

class PostListByCategory(ListView):

    def get_queryset(self):
        slug = self.kwargs["slug"]

        if slug == "_none":
            category = None
        else:
            category = Category.objects.get(slug=slug)

        return Post.objects.filter(category=category).order_by("-created")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostListByCategory, self).get_context_data(**kwargs)
        context["category_list"] = Category.objects.all()
        context["posts_without_category"] = Post.objects.filter(category=None).count()

        slug = self.kwargs["slug"]
        if slug == "_none":
            context["category"] = "미분류"
        else:
            category = Category.objects.get(slug=slug)
            context['category'] = category

        # context["title"] = "Blog - {}".format(category.name)
        return context

class PostListByTag(Post_List):
    model = Post

    def get_queryset(self):
        tag_slug = self.kwargs['slug']
        tag = Tag.objects.get(slug=tag_slug)
        return tag.post_set.order_by('-created')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(type(self), self).get_context_data(**kwargs)
        context["category_list"] = Category.objects.all()
        context["posts_without_category"] = Post.objects.filter(category=None).count()
        tag_slug = self.kwargs['slug']
        context['tag'] = Tag.objects.get(slug=tag_slug)
        return context

class PostUpdate(UpdateView):
    model = Post
    fields = [
        'title', 'content', 'head_image', 'category', 'tags'
    ]

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = [
        'title', 'content', 'head_image', 'category', 'tags'
    ]

    def form_valid(self, form):
        current_user = self.request.user #현재 사용중인 user 가져옴
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(type(self), self).form_valid(form)
        else:
            return redirect('/blog/')

def new_comment(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False) #db orm에 넣지마.
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect(comment.get_absolute_url())
    else:
        return redirect('/blog/')

# class CommentDelete(DeleteView):
#     model = Comment
#
#     def get_object(self, queryset=None):
#         comment = super(CommentDelete, self).get_object()
#         if comment.author != self.request.user:
#             raise PermissionError('삭제 권한이 없습니다.')
#         return comment
#
#     def get_success_url(self):
#         post = self.get_object().post
#         return post.get_absolute_url() + '#comment-list'

class CommentUpdate(UpdateView):
    model = Comment
    form_class = CommentForm

    def get_object(self, queryset=None):
        comment = super(CommentUpdate, self).get_object()
        if comment.author != self.request.user:
            raise PermissionError('Commnet 수정 권한이 없습니다.')

        return comment

def delete_comment(request, pk):
    comment = Comment.objects.get(pk=pk)
    post = comment.post

    if request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url() + '#comment-list')
    else:
        return PermissionError('Commnet를 삭제할 권한이 없습니다.')


# def post_detail(request, pk):
#     blog_post = Post.objects.get(pk=pk)
#
#     return render(request, "blog/post_detail.html", {
#         "blog_post" : blog_post,
#     })

# def index(request):
#     posts= Post.objects.all()
#
#     return render(
#         request,
#         "blog/post_list.html",
#         {
#             'posts':posts,
#         }
#     )

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}블랙커피의 블로그{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        body {
            padding-top: 56px;
        }
    </style>
</head>
<body>
<!-- navbar  -->
<div class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" id="navbar">
    <div class="container">
        <a href="{% url 'blog' %}" class="navbar-brand">Blackcoffee Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about_me/">About me</a>
                </li>
            </ul>

            <ul class="nav navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="blog-list">{{ user }}<span
                            class="caret"></span> </a>
                    <div class="dropdown-menu" aria-labelledby="themes">
                        <a class="dropdown-item" href="#">회원 관리(안됨)</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/accounts/logout/">로그아웃</a>
                    </div>
                </li>
                {% else %}
                    <li class="nav-item">
                        <!-- 버튼 트리거 모달 -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#gogle_login_modal">
                            로그인
                        </button>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

{% load socialaccount %}

<!-- Modal -->
<div class="modal fade" id="gogle_login_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">로그인을 해주시길 바랍니다.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <a role="button" class="btn btn-primary" href="{% provider_login_url 'google' %}"><span class="material-icons">input</span> 구글 로그인</a>
                        <a role="button" class="btn btn-danger" href="/accounts/login/"><span class="material-icons">email</span> 이메일 로그인</a>
                    </div>
                    <div class="col-md-6">
                        <a role="button" class="btn btn-danger" href="/accounts/signup/"><span class="material-icons">email</span> 이메일 회원가입</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<br>
<!-- 본문 -->
<div class="container">
    {% block blog_title %}{% endblock %}
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8" id="main-div">
            {% block content %}
            {% endblock %}

            <!-- Pagination -->
            {% block pagination %}
            {% endblock %}
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4" id="sid_div">

            <!-- Search Widget -->
            <div class="card my-4">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" id="search-input" onkeydown="wait_for_enterkey();" class="form-control" placeholder="Search for...">
                        <span class="input-group-append">
                <button class="btn btn-secondary" type="button" onclick="search_post();">Go!</button>
              </span>
                    </div>
                </div>
            </div>

            <!-- Categories Widget -->
            <div class="card my-4" id="category-card">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                {% for category in category_list %}
                                    <li>
                                        <a href="{{ category.get_absolute_url }}">{{ category.name }} ({{ category.post_set.count }})</a>
                                    </li>
                                {% endfor %}

                                <li>
                                    <a href="blog/category/_none/">미분류 ({{ posts_without_category }})</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.row -->
</div>
<script>
    function search_post() {
        var search_value = document.getElementById('search-input').value;
        location.href="/blog/search/" + search_value + "/";
    }
    
    function wait_for_enterkey() {
        if (window.event.keyCode == 13){
            search_post();
        }
    }
</script>
<script src="{% static 'blog/js/jquery.js' %}"></script>
<script src="{% static 'blog/js/popper.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.js' %}"></script>
<script src="{% static 'blog/js/custom.js' %}"></script>
</body>
</html>

blog/templates/blog/comment_confirm_delete.html
{% extends "blog/base.html" %}
{% block title %}{{ object.title }} - Blog{% endblock %}
{% block content %}
    <form method="post">{% csrf_token %}
        {{ object.get_markdown_content | safe }}
        <button type="submit" class="btn btn-primary">submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% block title %}{{ object.title }} - Blog{% endblock %}
{% block content %}
    <h3>Edit Comment : </h3>
    <form method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ object.title }} - Blog{% endblock %}
{% block content %}

    <!-- Title -->
    <h1 class="mt-4">{{ object.title }}</h1>

    {% if object.category %}
        <span class="badge badge-primary float-lg-right">{{ object.category }}</span>
    {% else %}
        <span class="badge badge-primary float-lg-right">미분류</span>
    {% endif %}

    <!-- Author -->
    <p class="lead">
        by
        <a href="#">{{ object.author.username }}</a>
    </p>
    {% if request.user == object.author %}
        <button type="button" class="btn btn-outline-secondary float-lg-right" onclick="location.href='{{ object.get_update_url }}'">EDIT</button>
    {% endif %}
    <hr>

    <!-- Date/Time -->
    <p>Posted on {{ object.created }}</p>

    <hr>

    <!-- Preview Image -->
    {% if object.head_image %}
        <img class="img-fluid rounded" src="{{ object.head_image.url }}" alt="{{ object.title }}">
    {% endif %}

    <!-- Post Content -->
    {{ object.get_markdown_content | safe}}

    <br>
    {% for tag in object.tags.all %}
        <a href="{{ tag.get_absolute_url }}">#{{ tag }}</a>
    {% endfor %}

    <!-- Comments Form -->
    <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
            {% if request.user.is_authenticated %}
            <form method="post" action="{{ object.get_absolute_url }}new_comment/">{% csrf_token %}
                <div class="form-group">
                    {{ comment_form | crispy }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% else %}
            <button type="button" class="btn btn-outline-dark btn-block" data-toggle="modal" data-target="#gogle_login_modal">
                로그인
            </button>
            {% endif %}
        </div>
    </div>

    <div id="comment-list">
        <!-- Single Comment -->
        {% for comment in object.comment_set.all %}
            <div class="media mb-4" id="comment-id-{{ comment.pk }}">
                {% if comment.author.socialaccount_set.all.0.get_avatar_url %}
                    <img class="d-flex mr-3 rounded-circle" width="50px" src="{{ comment.author.socialaccount_set.all.0.get_avatar_url }}" alt="profile-image">
                {% else %}
                    <img class="d-flex mr-3 rounded-circle" width="50px" src="https://api.adorable.io/avatars/285/{{ comment.author }}.png" alt="profile-image">
                {% endif %}
                <div class="media-body">
                    {% if comment.author == request.user %}
                        <button class="btn btn-sm btn-info float-right" onclick="location.href='/blog/edit_comment/{{ comment.pk }}/'">edit</button>
                        <button class="btn btn-sm btn-danger float-right" data-toggle="modal" data-target="#delete_comment_modal-{{ comment.pk }}">delete</button>
                    {% endif %}
                    <h5 class="mt-0">{{ comment.author }} <small class="text-muted">{{ comment.created_at }}</small></h5>
                    {{ comment.get_markdown_content | safe }}
                </div>
            </div>
        {% endfor %}
    </div>

    <!-- Modal -->
    {% for comment in object.comment_set.all %}
        {% if user == comment.author %}
            <div class="modal fade" id="delete_comment_modal-{{ comment.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">정말로 삭제하시겠습니까?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            {{ comment.get_markdown_content | safe }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" onclick="location.href='/blog/delete_comment/{{ comment.pk }}/'">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block title %}{{ object.title }} - Blog{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block blog_title %}
    {% if user.is_authenticated %}
        <button class="btn btn-primary float-right" onclick="location.href='/blog/create'">New Post</button>
    {% endif %}
    <h1 class="my-4" id="blog-list-title">
        Blackcoffee Blog
        {% if category %}<small class="text-muted">{{ category }}</small>{% endif %}
        {% if tag %}<small class="text-muted">: #{{ tag }}</small>{% endif %}
        {% if search_info %}<small class="text-muted">: {{ search_info }} ({{ object_list.count }})</small>{% endif %}
    </h1>
{% endblock %}

{% block content %}
    <!-- Blog Post -->
    {% if object_list.exists %}
        {% for object in  object_list %}
            <div class="card mb-4" id="post_card_{{ object.pk }}">
                {% if object.head_image %}
                    <img class="card-img-top" src="{{ object.head_image.url }}" alt="blog image">
                {% else %}
                    <img class="card-img-top" src="https://picsum.photos/750/300" alt="blog image">
                {% endif %}
                <div class="card-body">
                    {% if object.category %}
                        <span class="badge badge-primary float-lg-right">{{ object.category }}</span>
                    {% else %}
                       <span class="badge badge-primary float-lg-right">미분류</span>
                    {% endif %}

                    <h2 class="card-title"> {{ object.title }} </h2>
                    <p class="card-text"> {{ object.content | truncatewords:50 }} </p>
                    {% for tag in object.tags.all %}
                        <a href="{{ tag.get_absolute_url }}">#{{ tag }}</a>
                    {% endfor %}
                    <br><br>

                    <a href="{{ object.get_absolute_url }}" class="btn btn-primary" id="read_more_post_{{ object.pk }}">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    {{ object.created }} by {{ object.author }}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>아직 게시물이 없습니다.</h3>
    {% endif %}
{% endblock %}

{% block pagination %}
    {% if is_paginated %}
    <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr; Older</a>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link disabled" href="#">&larr; Older</a>
        {% endif %}
        </li>
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer &rarr;</a>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Newer &rarr;</a>
        {% endif %}
        </li>
    </ul>
    {% endif %}
{% endblock %}